In [2]:
my_list = [1,2,3]

In [3]:
import numpy as np

In [4]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [13]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
np.random.rand(5)

array([0.12574462, 0.2188367 , 0.41867374, 0.30558229, 0.43356099])

In [16]:
np.random.randn(2,2)

array([[-1.63747592, -1.05342186],
       [-1.88284619, -1.62627194]])

In [17]:
np.random.randint(1,100,10)

array([56,  7, 13, 72, 80, 38, 93, 56, 54, 63])

In [21]:
arr = np.arange(25)

In [19]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [23]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
arr.max()

24

In [25]:
arr.argmax()

24

In [26]:
arr.min()

0

In [27]:
arr.shape

(25,)

In [28]:
arr.dtype

dtype('int32')

In [29]:
from numpy.random import randint

In [31]:
randint(2,10)

8

In [32]:
#Numpy Array Indexing

In [33]:
arr = np.arange(0,11)

In [34]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
arr[1]

1

In [36]:
arr[4:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [37]:
arr[6:9]

array([6, 7, 8])

In [38]:
arr[0:5] = 100

In [48]:
import numpy as np

In [49]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [50]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
arr_2d[:1,1:]

array([[2, 3]])

In [52]:
bool_arr = arr >5

In [53]:
bool_arr

array([ True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True])

In [54]:
arr[arr>5]

array([100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [55]:
arr_2d = np.arange(50).reshape(5,10)

In [56]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [57]:
#NumPy Operation


In [58]:
import numpy as np

In [59]:
arr = np.arange(0,11)

In [60]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [62]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [63]:
arr+100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [64]:
arr/arr

C:\Users\NdivhudzannyiT\AppData\Local\Temp\ipykernel_5960\1862401812.py:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [65]:
1/arr

C:\Users\NdivhudzannyiT\AppData\Local\Temp\ipykernel_5960\255282349.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [66]:
arr**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [67]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])